### ISSUE TITLE
api setup 

### ISSUE THREAD

**Issue by basketbaseb** [basketbaseb/bible-fitbit#1]
Need to separate api controller from the web app controllers.
Update routes file to handle api subdomain POST/GET requests (ie biblefitbit.com/api/resource) which then will map to api controller and action.

**Comment by basketbaseb** [comment]
added app/controllers/api for eventual separate namespace for api controller. Just a placeholder for now, no code there. 

added in a6b7211d7c7e6ba22744158d6b5d2cc3180ca555

**Comment by basketbaseb** [comment]
dropped these changes, restructuring authentication

**Comment by cmylchan** [comment]
is there a chat room we can use or something? i need to learn the environment before i can be of any use
