### ISSUE TITLE
'Welcome mlen1990@gmail.com' should be 'Welcome <firstname><lastname.'

### ISSUE THREAD

**Issue by basketbaseb** [basketbaseb/bible-fitbit#31]

**Comment by basketbaseb** [comment]
Check the view for the home page, see where it's generating this text, and change it. should be simple

**Comment by cmylchan** [comment]
can do

**Comment by jonyen** [comment]
Can't do "<firstname> <lastname>" because the signup form is just username, email, and password.

**Comment by natyconnor** [comment]
@jonyen @cmylchan was planning on adding <firstname> and <lastname> to the User model and the sign up form. He started on the branch `add_fullname` so you can take a look, but he hadn't added the migration to add the columns to the table I don't think.

**Comment by cmylchan** [comment]
@jonyen @natyconnor 

I've added the migration on my local branch, got it working in the db (new columns added) but having difficulty connecting the form to the db

"firstname lastname" fields were added to the form, but when attempting to create a user, the info doesn't populate in the db

**Comment by cmylchan** [comment]
I committed and pushed my branch if you'd like to review

**Comment by natyconnor** [comment]
@cmylchan I'll take a look, but I'm guessing the form isn't hooking up right. The `form_for` function that surrounds the form fields does a lot of rails magic to connect the fields to the params which get passed to the action.

**Comment by jonyen** [comment]
Yeah, I got it working on my local setup.

Notably, you need to set the schema revision in schema.rb to the new
migration. Beyond that, it's pretty simple. I would've thought that rake
db:migrate would just update that for you, but seems like you have to do it
manually.

**Comment by cmylchan** [comment]
Okay yeah i was having trouble figuring out what goes where

schema.rb..

Really want to learn this so will try to get it to work, will bug ya if i
can't get it working locally c[=

                  Christopher Chan
