### ISSUE TITLE
authenticate_user! redirects to user/sign_up not api/user/sign_up

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/bible-fitbit#53]
Devise's `authenticate_user!` ends up redirecting to `user/sign_up` instead of `api/user/sign_up`. Try going to `timeline/index` when not logged in, and you will see it go to that url. Not sure how to fix this.

**Comment by basketbaseb** [comment]
are we still using authenticate_user!  ? I don't see it except in a commented out line

**Comment by natyconnor** [comment]
I don't think we're using it but we need to. Otherwise, a number of pages will give errors if you're not logged in since they just assume you are.
