### ISSUE TITLE
Use a CSS framework

### ISSUE THREAD

**Issue by jonyen** [basketbaseb/bible-fitbit#61]
The site is pretty barebones and needs some aesthetics. I think it would be good to implement a CSS framework. Susy looks like a good option: http://susy.oddbird.net/

**Comment by basketbaseb** [comment]
what about bootstrap?

**Comment by jonyen** [comment]
Yeah, I've looked at it, although not sure if it's well-suited for Rails.

**Comment by natyconnor** [comment]
I used this gem way back in the day. I think it was pretty easy: https://github.com/seyhunak/twitter-bootstrap-rails
