### ISSUE TITLE
JQuery doesn't load sometimes

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/bible-fitbit#66]
This is most noticeable on the friends page. Often times, the jquery for doing a friend search wont' work and you have to navigate to the page again.

I though this was this issue: https://stackoverflow.com/questions/25515634/rails-project-jquery-plugin-not-loading-until-refresh/25516013#25516013

but none of the solutions fully fixed the issue. Hopefully solving #65 will fix this as well.

**Comment by basketbaseb** [comment]
this worked for me
http://stackoverflow.com/questions/17600093/rails-javascript-not-loading-after-clicking-through-link-to-helper

**Comment by natyconnor** [comment]
I tried that and it only works some times. I put my code in `application.js` so take a look if you want.

**Comment by mlen1990** [comment]
Fixed the jquery bug on http://localhost:3000/api/friendships. Open another issue if there is another jquery not loading bug.
