### ISSUE TITLE
Notification that user can't be found to be added stays after animation

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/bible-fitbit#68]
The div containing the notification needs to be removed at the end of the animation, or at least `display: none`. Not only does this leave a gap after it's gone, but subsequent notifications appear below since the element is still there.

**Comment by mlen1990** [comment]
Pushed a temporary workaround to set the height and width of the div to 0 after 5 seconds. Didn't try display:none though.

**Comment by mlen1990** [comment]
Seems to work on my Mac's Chrome but not on Nathan's Firefox (Linux). Should we just remove the div with jquery?

**Comment by natyconnor** [comment]
Put in jquery to remove the div
