### ISSUE TITLE
Secure API with auth token

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/bible-fitbit#69]
If we're going to make an api for our app, we'll want it to be properly secure, in addition to plain working. Here are some pages for advice:

http://railscasts.com/episodes/352-securing-an-api?view=asciicast
http://railscasts.com/episodes/350-rest-api-versioning
https://github.com/lynndylanhurley/devise_token_auth -- add token auth to devise
http://stackoverflow.com/questions/21588781/rails-api-and-native-mobile-app-authentication

**Comment by basketbaseb** [comment]
forget it. will open in future if we go back to this.
