### ISSUE TITLE
nav menu covering webpage body

### ISSUE THREAD

**Issue by cmylchan** [basketbaseb/bible-fitbit#73]
Nav menu cuts off top section of webpage body 

![screen shot 2015-06-25 at 5 30 07 pm](https://cloud.githubusercontent.com/assets/12850316/8368511/265c75e6-1b60-11e5-8ab6-6f2778bf97f3.png)

**Comment by basketbaseb** [comment]
I fixed this on the home page, just need to add
```
padding-bottom: 75px;
```

**Comment by mlen1990** [comment]
Added margin-bottom: 90px to nav bar
