### ISSUE TITLE
Add percentage column to users_books table to keep track of progress on a book

### ISSUE THREAD

**Issue by mlen1990** [basketbaseb/bible-fitbit#75]
Also add an interface on the front-end for users to set the percentage completed for a book.

**Comment by natyconnor** [comment]
This is now possible if we want to do this with the `StudiedBook` model. Just add whatever columns you want to it. Not sure what percentage complete for a particular book would be though.

**Comment by basketbaseb** [comment]
do we still want to add percentages per book? I'm also not sure how we would track that.

**Comment by basketbaseb** [comment]
meh w/e doesn't make sense
