### ISSUE TITLE
fix header css across views

### ISSUE THREAD

**Issue by basketbaseb** [basketbaseb/bible-fitbit#85]

**Comment by basketbaseb** [comment]
seems to be specific to timeline related views. The header is getting it's font and color from this file:
app/assets/stylesheets/timeline/index/style.scss

**Comment by basketbaseb** [comment]
it's something in the timeline/timeline javascript link tag

**Comment by basketbaseb** [comment]
font-family: "Ruda",sans-serif;
font-size: 13px;

set for the body in reset.css is overriding the bootstrap header css

**Comment by basketbaseb** [comment]
also need to comment out `a { blah blah }` in style.scss

**Comment by natyconnor** [comment]
This looks fixed to me. Did @mlen1990 work on it or did it just fix itself?

**Comment by mlen1990** [comment]
Oh yah I fixed it.
