### ISSUE TITLE
Migrate to Cloud9 development environment 

### ISSUE THREAD

**Issue by basketbaseb** [basketbaseb/bible-fitbit#87]

**Comment by natyconnor** [comment]
Running on cloud9 here: https://bible-fitbit-natyconnor.c9.io/

People will need sign up for cloud 9 for me to share the workspace.

**Comment by natyconnor** [comment]
Free account only allows 1 workspace so we'd essentially be sharing one computer which is not very useful. Good for anyone to use if they don't have access to their work machine I guess.
