### ISSUE TITLE
Set Up Heroku to use a different Web Server

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/bible-fitbit#89]
Using the default WEBrick may not be the best, especially for performance. Need to do some research and try out some different servers.

**Comment by basketbaseb** [comment]
should look into Unicorn

**Comment by basketbaseb** [comment]
https://devcenter.heroku.com/articles/ruby-default-web-server

**Comment by basketbaseb** [comment]
seems heroku recommends puma

**Comment by basketbaseb** [comment]
closing until needed
