### ISSUE TITLE
Add Progress button on Timeline page doesn't work well

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/bible-fitbit#91]
It's a link within a button so it kind of acts strange. Need to have mouse directly over text to work, but button still changes color when over it, not text. Doesn't work at all on firefox. Should just use a link and style it.

**Comment by natyconnor** [comment]
use `link_to` function and give it the classes `btn btn-default`. That should give it bootstrap's button css but function as a link.

**Comment by mlen1990** [comment]
Fixed.
