### ISSUE TITLE
Home Page should show something different if you're not logged in

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/bible-fitbit#93]
Info in dashboard doesn't make any sense if you're not logged in. Like any website, you should have to log in to see anything. Homepage should have a welcome or something instead if you're not logged in.

**Comment by basketbaseb** [comment]
I like how the spotify app handles this, it shows you login/signup buttons with a video playing in the background and goes to another one once it's over. Maybe we could put martin's gif.

**Comment by natyconnor** [comment]
Just put an image for now.

**Comment by natyconnor** [comment]
Not having any success with a video. If we want, we can add that as an enhancement. This bug is fixed though.
